name: Chiste de Chuck Norris

on:
  schedule:
    - cron: '0 * * * *'  # Ejecutar cada hora

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Get Chuck Norris joke
        run: |
          python -c "import requests
          url = 'https://api.chucknorris.io/jokes/random'
          response = requests.get(url)
          if response.status_code == 200:
              data = response.json()
              print(data['value'])
          else:
              print('Error al obtener el chiste')"
